/* The following script is derived heavily from the script that appears
in the html exports generated by the program FreeMind.  http://freemind.sf.net

FreeMind is a very beautifully written program that the authors describe
as a Mind Mapper.  It allows for editing of trees of text in a very natural way,
and has a set of very intuitive key bindings.  It can export the trees as html,
and uses javascript to allow expanding and collapsing of nodes.

I normally don't lift code from other projects, but the quirks of the various
browsers out there require the touch of a HTML/Javascript/CSS master in order
to get things to work, and I just don't have that level of expertise.

*/

// Here we implement folding. It works fine with MSIE5.5, MSIE6.0 and
// Mozilla 0.9.6.
if (document.layers) {
	//Netscape 4 specific code
	pre= 'document.';
	post= '';
}
if (document.getElementById) {
	//Netscape 6 specific code
	pre= 'document.getElementById(\"';
	post= '\").style';
}
if (document.all) {
	//IE4+ specific code
	pre= 'document.all.';
	post= '.style';
}

function layer_exists(layer) {
	try {
		eval(pre+layer+post);
		return true;
	}
	catch (error) {
		return false;
	}
}
function show_layer(layer) {
	eval(pre+layer+post).visibility= 'visible';
	eval(pre+layer+post).position= 'relative';
}
function hide_layer(layer) {
	eval(pre+layer+post).position= 'absolute';
	eval(pre+layer+post).visibility= 'hidden';
}
function select_recursive(Path, Index, AffectChildren) {
	var i;
	if (AffectChildren)
		for (i=0; layer_exists(Path+'_'+i); i++)
			select_recursive(Path+'_'+i, Index, AffectChildren);
	for (i=0; layer_exists(Path+'c'+i); i++)
		if (i == Index)
			show_layer(Path+'c'+i);
		else
			hide_layer(Path+'c'+i);
}

function SelectContent(Path, ContentIndex, AffectChildren) {
	select_recursive(Path, ContentIndex, AffectChildren);
	scrollBy(0,0); // work-around for buggy browsers
}
